# Build stage
FROM microsoft/aspnetcore-build:lastest AS build-env

WORKDIR /generator

# restore
COPY api/api.csproj ./api/
RUN dotnet restore api/api.csproj
COPY tests/tests.csproj ./tests/
RUN dotnet restore tests/tests.csproj

# copy src

# tests

# publish



# Runtime stage